//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PayX.com.branchcollect.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BranchCollectWebServicesGTBinding", Namespace="http://branchcollect.com/sk/pa")]
    public partial class BranchCollectWebServicesGT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateTransactionTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateTransactionV3Dot2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateTransactionV3Dot3OperationCompleted;
        
        private System.Threading.SendOrPostCallback PaidTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnePaidTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaidTransactionDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BranchCollectWebServicesGT() {
            this.Url = global::PayX.Properties.Settings.Default.PayxNew_com_branchcollect_www_BranchCollectWebServicesGT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateTransactionCompletedEventHandler GenerateTransactionCompleted;
        
        /// <remarks/>
        public event GenerateTransactionTPCompletedEventHandler GenerateTransactionTPCompleted;
        
        /// <remarks/>
        public event GenerateTransactionV3Dot2CompletedEventHandler GenerateTransactionV3Dot2Completed;
        
        /// <remarks/>
        public event GenerateTransactionV3Dot3CompletedEventHandler GenerateTransactionV3Dot3Completed;
        
        /// <remarks/>
        public event PaidTransactionCompletedEventHandler PaidTransactionCompleted;
        
        /// <remarks/>
        public event OnePaidTransactionCompletedEventHandler OnePaidTransactionCompleted;
        
        /// <remarks/>
        public event PaidTransactionDetailsCompletedEventHandler PaidTransactionDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/GenerateTransactio" +
            "n", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GenerateTransaction(string XMLRequest) {
            object[] results = this.Invoke("GenerateTransaction", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTransactionAsync(string XMLRequest) {
            this.GenerateTransactionAsync(XMLRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTransactionAsync(string XMLRequest, object userState) {
            if ((this.GenerateTransactionOperationCompleted == null)) {
                this.GenerateTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTransactionOperationCompleted);
            }
            this.InvokeAsync("GenerateTransaction", new object[] {
                        XMLRequest}, this.GenerateTransactionOperationCompleted, userState);
        }
        
        private void OnGenerateTransactionOperationCompleted(object arg) {
            if ((this.GenerateTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTransactionCompleted(this, new GenerateTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/GenerateTransactio" +
            "nTP", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GenerateTransactionTP(string XMLRequest) {
            object[] results = this.Invoke("GenerateTransactionTP", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTransactionTPAsync(string XMLRequest) {
            this.GenerateTransactionTPAsync(XMLRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTransactionTPAsync(string XMLRequest, object userState) {
            if ((this.GenerateTransactionTPOperationCompleted == null)) {
                this.GenerateTransactionTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTransactionTPOperationCompleted);
            }
            this.InvokeAsync("GenerateTransactionTP", new object[] {
                        XMLRequest}, this.GenerateTransactionTPOperationCompleted, userState);
        }
        
        private void OnGenerateTransactionTPOperationCompleted(object arg) {
            if ((this.GenerateTransactionTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTransactionTPCompleted(this, new GenerateTransactionTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/GenerateTransactio" +
            "nV3Dot2", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GenerateTransactionV3Dot2(string XMLRequest) {
            object[] results = this.Invoke("GenerateTransactionV3Dot2", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTransactionV3Dot2Async(string XMLRequest) {
            this.GenerateTransactionV3Dot2Async(XMLRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTransactionV3Dot2Async(string XMLRequest, object userState) {
            if ((this.GenerateTransactionV3Dot2OperationCompleted == null)) {
                this.GenerateTransactionV3Dot2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTransactionV3Dot2OperationCompleted);
            }
            this.InvokeAsync("GenerateTransactionV3Dot2", new object[] {
                        XMLRequest}, this.GenerateTransactionV3Dot2OperationCompleted, userState);
        }
        
        private void OnGenerateTransactionV3Dot2OperationCompleted(object arg) {
            if ((this.GenerateTransactionV3Dot2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTransactionV3Dot2Completed(this, new GenerateTransactionV3Dot2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/GenerateTransactio" +
            "nV3Dot3", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GenerateTransactionV3Dot3(string XMLRequest) {
            object[] results = this.Invoke("GenerateTransactionV3Dot3", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTransactionV3Dot3Async(string XMLRequest) {
            this.GenerateTransactionV3Dot3Async(XMLRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTransactionV3Dot3Async(string XMLRequest, object userState) {
            if ((this.GenerateTransactionV3Dot3OperationCompleted == null)) {
                this.GenerateTransactionV3Dot3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTransactionV3Dot3OperationCompleted);
            }
            this.InvokeAsync("GenerateTransactionV3Dot3", new object[] {
                        XMLRequest}, this.GenerateTransactionV3Dot3OperationCompleted, userState);
        }
        
        private void OnGenerateTransactionV3Dot3OperationCompleted(object arg) {
            if ((this.GenerateTransactionV3Dot3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTransactionV3Dot3Completed(this, new GenerateTransactionV3Dot3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/PaidTransaction", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string PaidTransaction(string XMLRequest) {
            object[] results = this.Invoke("PaidTransaction", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaidTransactionAsync(string XMLRequest) {
            this.PaidTransactionAsync(XMLRequest, null);
        }
        
        /// <remarks/>
        public void PaidTransactionAsync(string XMLRequest, object userState) {
            if ((this.PaidTransactionOperationCompleted == null)) {
                this.PaidTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaidTransactionOperationCompleted);
            }
            this.InvokeAsync("PaidTransaction", new object[] {
                        XMLRequest}, this.PaidTransactionOperationCompleted, userState);
        }
        
        private void OnPaidTransactionOperationCompleted(object arg) {
            if ((this.PaidTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaidTransactionCompleted(this, new PaidTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/OnePaidTransaction" +
            "", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string OnePaidTransaction(string XMLRequest) {
            object[] results = this.Invoke("OnePaidTransaction", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnePaidTransactionAsync(string XMLRequest) {
            this.OnePaidTransactionAsync(XMLRequest, null);
        }
        
        /// <remarks/>
        public void OnePaidTransactionAsync(string XMLRequest, object userState) {
            if ((this.OnePaidTransactionOperationCompleted == null)) {
                this.OnePaidTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnePaidTransactionOperationCompleted);
            }
            this.InvokeAsync("OnePaidTransaction", new object[] {
                        XMLRequest}, this.OnePaidTransactionOperationCompleted, userState);
        }
        
        private void OnOnePaidTransactionOperationCompleted(object arg) {
            if ((this.OnePaidTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnePaidTransactionCompleted(this, new OnePaidTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.branchcollect.com/branchcollect_test/pay/index.php/PaidTransactionDet" +
            "ails", RequestNamespace="http://branchcollect.com/sk/pa", ResponseNamespace="http://branchcollect.com/sk/pa")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string PaidTransactionDetails(string XMLRequest) {
            object[] results = this.Invoke("PaidTransactionDetails", new object[] {
                        XMLRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaidTransactionDetailsAsync(string XMLRequest) {
            this.PaidTransactionDetailsAsync(XMLRequest, null);
        }
        
        /// <remarks/>
        public void PaidTransactionDetailsAsync(string XMLRequest, object userState) {
            if ((this.PaidTransactionDetailsOperationCompleted == null)) {
                this.PaidTransactionDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaidTransactionDetailsOperationCompleted);
            }
            this.InvokeAsync("PaidTransactionDetails", new object[] {
                        XMLRequest}, this.PaidTransactionDetailsOperationCompleted, userState);
        }
        
        private void OnPaidTransactionDetailsOperationCompleted(object arg) {
            if ((this.PaidTransactionDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaidTransactionDetailsCompleted(this, new PaidTransactionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GenerateTransactionCompletedEventHandler(object sender, GenerateTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GenerateTransactionTPCompletedEventHandler(object sender, GenerateTransactionTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTransactionTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTransactionTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GenerateTransactionV3Dot2CompletedEventHandler(object sender, GenerateTransactionV3Dot2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTransactionV3Dot2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTransactionV3Dot2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GenerateTransactionV3Dot3CompletedEventHandler(object sender, GenerateTransactionV3Dot3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTransactionV3Dot3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTransactionV3Dot3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PaidTransactionCompletedEventHandler(object sender, PaidTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaidTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaidTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OnePaidTransactionCompletedEventHandler(object sender, OnePaidTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnePaidTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnePaidTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PaidTransactionDetailsCompletedEventHandler(object sender, PaidTransactionDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaidTransactionDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaidTransactionDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591